server:
  port: 80
  address: 127.0.0.1
jdbc:
  dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
  url: jdbc:mysql://192.168.169.100:3306/BOOT_DEMO?useUnicode=true&amp;charaterEncoding=utf-8
  databaseName: BOOT_DEMO
  serverName: 192.168.169.100
  username: root
  password: 123
  cachePrepStmts: true
  prepStmtsSize: 250
  prepStmtsCacheSqlLimit: 2048
  userServerPrepStmts: true
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
mybatis: 
  typeAliasesPackage: com.wang.springboot.mySpringBoot.**.domain
  mapperLocations: classpath:/com/wang/springboot/mySpringBoot/api/**/dao/*.xml
  configLocation: classpath:/mybatis-config.xml
logging:
  path: ./logs
  file: myapp.log
  level: 
    org.springframework.transaction: TRACE 
    com.ibatis: DEBUG