CREATE DATABASE BOOT_DEMO;

CREATE TABLE ACCOUNT(
	ID VARCHAR(64) NOT NULL PRIMARY KEY , 
	NAME VARCHAR(64) NOT NULL , 
	EMAIL VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	ACTIVATED BOOLEAN,
	CREATED_BY VARCHAR(50),
	CREATED_DATE DATE,
	LAST_MODIFIED_BY VARCHAR(50),
	LAST_MODIFIED_DATE DATE
);